#!/usr/bin/env python3
"""Generate src/it_help.inc from the original IT_H.ASM help data.

IT_H.ASM keeps the context-sensitive F1 help as data: per-context lists
of line pointers (HelpContextNPtrs / NoHelpContext), the line strings
(first byte = start column, then text with 0FFh repeat and 0FEh
attribute codes, and bytes 80h..0CEh naming dictionary words), and the
dictionary itself (DecodeWord80h..).  This script transliterates that
data 1:1 into C tables; H_DrawHelp's decoder lives in it_editor.c.

Usage: python tools/gen_help.py ../impulsetracker/IT_H.ASM src/it_help.inc
"""
import re
import sys

SWITCHES = {'SAVESAMPLEWAV': 1}     # SWITCH.INC of the 2.14/2.17 build


def parse_values(text):
    """TASM DB operand list -> list of byte values."""
    out, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if c in ' \t,':
            i += 1
        elif c == ';':
            break
        elif c in '\'"':
            j = text.index(c, i + 1)
            out.extend(ord(ch) for ch in text[i + 1:j])
            i = j + 1
        else:
            m = re.match(r'[0-9A-Fa-f]+[hH]?', text[i:])
            tok = m.group(0)
            out.append(int(tok[:-1], 16) if tok[-1] in 'hH' else int(tok))
            i += len(tok)
    return out


def add_offsets(lst, rest):
    for part in rest.split(';')[0].split(','):
        part = part.strip()
        if part.startswith('Offset'):
            lst.append(part.split()[1].lower())
        elif part == '0':
            lst.append(None)


def main(src, dst):
    lines = open(src, encoding='latin-1').read().split('\n')
    strings, lists, order = {}, {}, []
    cur = None                      # (kind, label)
    skip = []                       # IF/ELSE stack of "active" flags
    for raw in lines:
        line = raw.rstrip()
        s = line.strip()
        up = s.upper()
        if up.startswith('IF '):
            skip.append(bool(SWITCHES.get(s.split()[1], 0)))
            continue
        if up == 'ELSE':
            skip[-1] = not skip[-1]
            continue
        if up == 'ENDIF':
            skip.pop()
            continue
        if skip and not all(skip):
            continue
        m = re.match(r'^([A-Za-z_]\w*)\s+(DB|DW|Label)\b\s*(.*)$', line)
        if m:
            label, kind, rest = m.groups()
            label = label.lower()           # TASM labels ignore case
            if 'Dup' in rest:               # DecodeBuffer, Positions
                cur = None
                continue
            if kind == 'DB':
                strings[label] = parse_values(rest)
                order.append(label)
                cur = ('DB', label)
            elif kind == 'Label' or (kind == 'DW' and 'Offset' in rest):
                lists[label] = []
                cur = ('DW', label)
                if kind == 'DW':
                    add_offsets(lists[label], rest)
            else:
                cur = None
            continue
        m = re.match(r'^\s+(DB|DW)\s+(.*)$', line)
        if m and cur:
            kind, rest = m.groups()
            if kind == 'DB' and cur[0] == 'DB':
                strings[cur[1]].extend(parse_values(rest))
            elif kind == 'DW' and cur[0] == 'DW':
                add_offsets(lists[cur[1]], rest)
            continue
        if s and not s.startswith(';'):
            cur = None

    ctx = lists['helpcontextptrs']
    words = lists['decodewords']
    used = set()
    for name in set(ctx):
        for ent in lists[name]:
            if ent:
                used.add(ent)
    used.update(words)

    o = []
    o.append('/* Generated by tools/gen_help.py from IT_H.ASM -- do not edit.')
    o.append(' * Context-sensitive F1 help of Impulse Tracker, transliterated 1:1:')
    o.append(' * line strings (start column, text, 0FFh repeat, 0FEh attribute,')
    o.append(' * 80h..0CEh = dictionary words), the dictionary and the per-context')
    o.append(' * line lists (NULL-terminated). */')
    for label in order:
        if label in used:
            data = strings[label]
            body = ', '.join('0x%02X' % b for b in data)
            o.append('static const uint8_t HLP_%s[] = { %s };' % (label, body))
    o.append('')
    o.append('static const uint8_t *const HelpDecodeWords[%d] = {' % len(words))
    for w in words:
        o.append('    HLP_%s,' % w)
    o.append('};')
    o.append('')
    for name in dict.fromkeys(ctx):
        o.append('static const uint8_t *const HLPL_%s[] = {' % name)
        for ent in lists[name]:
            o.append('    %s,' % ('HLP_' + ent if ent else 'NULL'))
        if lists[name][-1] is not None:
            o.append('    NULL,')
        o.append('};')
    o.append('')
    o.append('static const uint8_t *const *const HelpContextPtrs[%d] = {' % len(ctx))
    for name in ctx:
        o.append('    HLPL_%s,' % name)
    o.append('};')
    open(dst, 'w', encoding='latin-1', newline='\n').write('\n'.join(o) + '\n')
    print('%d strings, %d words, %d contexts' % (len(used), len(words), len(ctx)))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
