#!/usr/bin/env python3
"""
gen_vgadata.py -- generate src/it_vgadata.c from the original IT_S.ASM.

Extracts, byte-exact:
  - PaletteDefs        (default "Camouflage" palette, 16x RGB, 6-bit VGA)
  - CharacterDefinitions (custom UI glyphs, chars 128..201, 8x8 bitmaps)
  - BoxDefinitions     (box styles, 9 (char,attr) pairs each)
plus the 8x8 CP437 font (tools/IBM_VGA_8x8.bin, the IBM VGA ROM font
that int 10h AX=1112h loads -- exactly what IT ran on top of).  Custom
glyphs 128.. override the ROM font exactly as S_InitScreen's
S_RedefineCharacters call does.

Usage: python gen_vgadata.py <impulsetracker-src-dir> <romfont.bin> <out.c>
"""
import re
import sys

def parse_db_values(line):
    # strip comment
    line = line.split(';', 1)[0]
    m = re.search(r'\bDB\s+(.*)', line, re.IGNORECASE)
    if not m:
        return None
    vals = []
    for tok in m.group(1).split(','):
        tok = tok.strip()
        if not tok:
            continue
        if re.fullmatch(r'[0-9][0-9A-Fa-f]*h', tok):
            vals.append(int(tok[:-1], 16))
        elif re.fullmatch(r'\d+', tok):
            vals.append(int(tok))
        else:
            return None  # string/label line -> not raw bytes
    return vals if vals else None

def extract_block(lines, start_label, end_label):
    out = []
    in_block = False
    in_comment = False
    for ln in lines:
        s = ln.strip()
        if not in_block:
            if s.startswith(start_label):
                in_block = True
            continue
        if s.startswith(end_label):
            break
        if in_comment:
            if '&' in s:
                in_comment = False
            continue
        if re.match(r'Comment\s*&', s, re.IGNORECASE):
            in_comment = True
            continue
        if s.startswith(';'):
            continue
        if re.match(r'IF\b|ENDIF\b|ELSE\b', s):  # IF TUTORIAL block: skip body
            # treat IF..ENDIF body as excluded (TUTORIAL=0 in release)
            in_comment = '&IF&'  # sentinel: skip until ENDIF
            continue
        if in_comment == '&IF&':
            if s.startswith('ENDIF'):
                in_comment = False
            continue
        v = parse_db_values(ln)
        if v:
            out.extend(v)
    return out

def main():
    srcdir, fontpath, outpath = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(srcdir + '/IT_S.ASM', encoding='cp437') as f:
        lines = f.readlines()

    # ---- palette: first 4 DB lines after PaletteDefs ----
    pal = extract_block(lines, 'PaletteDefs', 'PresetPalettes')
    assert len(pal) == 48, f'palette: got {len(pal)}'

    chars = extract_block(lines, 'CharacterDefinitions',
                          'EndCharacterDefinitions')
    assert len(chars) % 8 == 0, f'chars: got {len(chars)}'
    nchars = len(chars) // 8
    assert nchars == 74, f'expected 74 custom glyphs (128..201), got {nchars}'

    boxes = extract_block(lines, 'BoxDefinitions',
                          'CharacterGenerationOffset')
    assert len(boxes) % 18 == 0, f'boxes: got {len(boxes)}'
    nboxes = len(boxes) // 18

    # ---- HexNumeralDefinitions: 4px-wide numerals 0-9 A-F G H used by
    # S_DefineSmallNumbers (info page hex-pair charset + G0..H9 glyphs).
    # NB the original table's '0' row has only 7 bytes, so every glyph
    # n>=1 at offset n*8 is shifted by one byte -- part of the authentic
    # look; keep the raw layout and pad the tail to 18*8 with the byte
    # the original would read next (BoxDefinitions[0] = 128).
    hexnum = extract_block(lines, 'HexNumeralDefinitions',
                           'BoxDefinitions')
    assert len(hexnum) == 143, f'hexnums: got {len(hexnum)}'
    hexnum.append(boxes[0])

    # ---- ROM 8x8 font ----
    font = open(fontpath, 'rb').read()
    assert len(font) == 2048, f'font: got {len(font)} bytes, want 2048'
    # sanity: glyph 1 = the classic smiley, space blank
    assert font[8:16] == bytes([0x7E,0x81,0xA5,0x81,0xBD,0x99,0x81,0x7E])
    assert font[0x20*8:0x21*8] == b'\0' * 8
    import os
    fontsrc = os.path.basename(fontpath)

    with open(outpath, 'w', newline='\n') as f:
        w = f.write
        w('/*\n'
          ' * it_vgadata.c -- generated by tools/gen_vgadata.py. DO NOT EDIT.\n'
          ' *\n'
          ' * Byte-exact data from the original Impulse Tracker source:\n'
          ' *   IT_PaletteDefs  = IT_S.ASM PaletteDefs (default "Camouflage",\n'
          ' *                     16 x RGB, 6-bit VGA DAC values 0..63)\n'
          ' *   IT_CharDefs     = IT_S.ASM CharacterDefinitions (UI glyphs\n'
          ' *                     128..201, 8x8 bitmaps, MSB = left pixel)\n'
          ' *   IT_BoxDefs      = IT_S.ASM BoxDefinitions (box styles,\n'
          ' *                     9 x (char,attr): TL,T,TR,L,fill,R,BL,B,BR)\n'
          ' *   IT_HexNumerals  = IT_S.ASM HexNumeralDefinitions (4px-wide\n'
          ' *                     numerals 0-9 A-F G H for the info page\'s\n'
          ' *                     small-number charsets, S_DefineSmallNumbers).\n'
          ' *                     The original \'0\' row is only 7 bytes, so\n'
          ' *                     glyphs 1.. read one byte early and \'H\'\n'
          ' *                     reads BoxDefinitions[0]=128 as its last\n'
          ' *                     row -- authentic quirk, preserved.\n'
          f' *   IT_FontROM      = IBM VGA ROM 8x8 font (CP437), the font\n'
          f' *                     int 10h AX=1112h loads ({fontsrc})\n'
          ' */\n\n#include "it_vgadata.h"\n\n')

        w('const uint8_t IT_PaletteDefs[48] = {\n')
        for i in range(0, 48, 12):
            w('    ' + ', '.join('%2d' % v for v in pal[i:i+12]) + ',\n')
        w('};\n\n')

        w('const uint8_t IT_CharDefs[%d][8] = {\n' % nchars)
        for i in range(nchars):
            row = chars[i*8:(i+1)*8]
            w('    {' + ','.join('0x%02X' % v for v in row) +
              '}, /* %d */\n' % (128 + i))
        w('};\n\n')

        w('const uint8_t IT_BoxDefs[%d][18] = {\n' % nboxes)
        for i in range(nboxes):
            row = boxes[i*18:(i+1)*18]
            w('    {' + ','.join(('0x%02X' % v) for v in row) +
              '}, /* style %d */\n' % i)
        w('};\n\n')

        w('const uint8_t IT_HexNumerals[144] = {\n')
        for i in range(0, 144, 8):
            w('    ' + ','.join('0x%02X' % v for v in hexnum[i:i+8]) +
              ', /* +%d */\n' % i)
        w('};\n\n')

        w('const uint8_t IT_FontROM[256][8] = {\n')
        for c in range(256):
            row = font[c*8:(c+1)*8]
            w('    {' + ','.join('0x%02X' % v for v in row) +
              '}, /* %3d */\n' % c)
        w('};\n')

    print(f'palette 48 bytes, {nchars} glyphs, {nboxes} box styles, '
          f'font from {fontsrc}')

if __name__ == '__main__':
    main()
