#!/usr/bin/env python3
"""art/corner.bmp -> src/it_cornerart.{c,h}

Embeds the port's corner-art badge (an uncompressed 8-bit palettized
BMP) as palette indices plus a 0xRRGGBB lookup table so the rasterizer
in it_screen.c can blit it without a runtime file dependency.  The
generated files are committed; rerun only when the artwork changes:

    python tools/gen_cornerart.py art/corner.bmp src/it_cornerart
"""

import struct
import sys


def load_bmp8(path):
    d = open(path, "rb").read()
    if d[:2] != b"BM":
        sys.exit(f"{path}: not a BMP")
    off = struct.unpack_from("<I", d, 10)[0]
    hdrsize = struct.unpack_from("<I", d, 14)[0]
    w, h = struct.unpack_from("<ii", d, 18)
    planes, bpp = struct.unpack_from("<HH", d, 26)
    comp = struct.unpack_from("<I", d, 30)[0]
    if hdrsize < 40 or planes != 1 or bpp != 8 or comp != 0:
        sys.exit(f"{path}: need an uncompressed 8-bit BMP "
                 f"(hdr {hdrsize}, planes {planes}, bpp {bpp}, comp {comp})")
    ncol = struct.unpack_from("<I", d, 46)[0] or 256
    pal = []
    for i in range(ncol):
        b, g, r = d[14 + hdrsize + i*4: 14 + hdrsize + i*4 + 3]
        pal.append((r << 16) | (g << 8) | b)
    topdown = h < 0
    h = abs(h)
    stride = (w + 3) & ~3
    rows = []
    for y in range(h):
        sy = y if topdown else h - 1 - y
        rows.append(d[off + sy*stride: off + sy*stride + w])
    return w, h, pal, rows


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__.strip())
    src, out = sys.argv[1], sys.argv[2]
    w, h, pal, rows = load_bmp8(src)
    npal = max(max(r) for r in rows) + 1
    pal = pal[:npal]

    with open(out + ".h", "w", newline="\n") as f:
        f.write(f"""/*
 * it_cornerart.h
 * --------------
 * The port's corner-art badge ({w}x{h}, {npal}-entry palette).
 * Generated into it_cornerart.c by tools/gen_cornerart.py from
 * art/corner.bmp.
 */

#ifndef IT_CORNERART_DATA_H
#define IT_CORNERART_DATA_H

#include <stdint.h>

#define IT_CORNERART_W {w}
#define IT_CORNERART_H {h}

/* 0xRRGGBB per palette index */
extern const uint32_t IT_CornerArtPal[{npal}];
extern const uint8_t IT_CornerArt[IT_CORNERART_H][IT_CORNERART_W];

#endif /* IT_CORNERART_DATA_H */
""")

    with open(out + ".c", "w", newline="\n") as f:
        f.write("/*\n"
                " * it_cornerart.c -- generated by tools/gen_cornerart.py"
                " from art/corner.bmp.\n"
                " * DO NOT EDIT.\n"
                " */\n\n"
                '#include "it_cornerart.h"\n\n')
        f.write(f"const uint32_t IT_CornerArtPal[{npal}] = {{\n")
        for i in range(0, npal, 6):
            f.write("    " + " ".join(f"0x{c:06X}," for c in pal[i:i+6])
                    + "\n")
        f.write("};\n\n")
        f.write(f"const uint8_t IT_CornerArt[IT_CORNERART_H]"
                f"[IT_CORNERART_W] = {{\n")
        for r in rows:
            f.write("    {" + ",".join(str(v) for v in r) + "},\n")
        f.write("};\n")

    print(f"{out}.c/.h: {w}x{h}, {npal} palette entries")


if __name__ == "__main__":
    main()
